### ISSUE TITLE
Prevent self-vetting by author

### ISSUE THREAD

**Issue by mezis** [mezis/appfab#118]

**Comment by pedrocunha** [comment]
I think this one is fixed

**Comment by mezis** [comment]
I'm not seeing anything in the codebase that would prevent this. Also, I definitely just reproduced it in my production test account.

**Comment by pedrocunha** [comment]
On a fresh start, last time after I create an idea I could not vet it! Unless there is a time delta that prevents vetting right away! Is that the case (sorry only checked this through the UI)

**Comment by mezis** [comment]
I did check it through the UI as well, and I definitely could vet it. Perhaps you tried in an account where you don't have permissions to vet?

**Comment by HashNuke** [comment]
@mezis @pedrocunha I sent a PR to fix this https://github.com/mezis/appfab/pull/212
