### ISSUE TITLE
Clarify user roles

### ISSUE THREAD

**Issue by sdorunga** [mezis/appfab#128]
Currently on the user profile page I can only see that I can not edit my roles if I am not an admin. I cannot however see what roles I currently have.

I can figure it out by hovering over them and checking if I can't create or I can't destroy, but I believe this is not ideal.

Proposed solution: 

Create a different style for active roles that is different from the inactive ones.

(I may pick this one up myself, but I figured it's good to have it here)

**Comment by mezis** [comment]
I revisited this stlightly as to make the Sass tweak as painless as possible (thinking of the big Bootstrap 3 upgrade ahead).

You can check it out on [staging](http://appfab-staging.herokuapp.com), tell me what you think.

Closing for now.

**Comment by sdorunga** [comment]
That looks great. Funny thing about the colorscheme, I choose the previous color because I didn't know what the top of the app looks like, since I always see a giant orange banner, so to my eyes it fit in quite nicely :D
