### ISSUE TITLE
Instant feedback on score change

### ISSUE THREAD

**Issue by sdorunga** [mezis/appfab#129]
It would be nice if on activities that increase/decrease the user would get instant feedback by getting a live change in score. Currently you have to refresh the page, while the interface you interact with is updating itself quite nicely

**Comment by mezis** [comment]
There's a plan to have a pusher integration. But admittedly—AJAX actions should update this too.
I'm thinking comments in particular.

Adding to the roadmap.

**Comment by mezis** [comment]
Fixed in #140.
