### ISSUE TITLE
Do not notify for own comments, votes, vettings

### ISSUE THREAD

**Issue by mezis** [mezis/appfab#141]

**Comment by mamadoutoure** [comment]
Hi !

do you guys mind me working in this issue ?

**Comment by mezis** [comment]
Hi @mamadoutoure, we wouldn't mind at all! Enjoy, and ask for help if you need any.

**Comment by mamadoutoure** [comment]
Hi Mezis

I've just finsihed the setup of the rails project on my machine. I'm able to run it locally, but I need to feed the tables with data. Is there some seeds that I can run to populate my tables. And could you please tell me how to recreate this issue ?

**Comment by mezis** [comment]
> I've just finsihed the setup of the rails project on my machine. I'm able to run it locally, but I need to feed the tables with data. Is there some seeds that I can run to populate my tables. And could you please tell me how to recreate this issue ?

Normally you shouldn't need any data at all.
You can recreate the issue by firing up the server (with `rails server`), logging in, creating an idea, and commenting on it. The Rails logs should show that it sent you an email (of course locally it won't, but that's how you can detect it).

First thing is probably to write a spec for this.

**Comment by mamadoutoure** [comment]
I ran it locally, add a comment and checked my logs, but there is no trace of email sent, but just an insert on notification table like this one:
SQL (4.2ms)  INSERT INTO `notifications` (`body`, `created_at`, `recipient_id`, `subject_id`, `subject_type`, `type`, `unread`, `updated_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)  [["body", nil], ["created_at", Sun, 22 Sep 2013 18:11:57 UTC +00:00], ["recipient_id", 2], ["subject_id", 11], ["subject_type", "Comment"], ["type", "Notification::NewComment"], ["unread", true], ["updated_at", Sun, 22 Sep 2013 18:11:57 UTC +00:00]]

**Comment by mezis** [comment]
That's normal—and is the current behaviour. In-app notifications are instant (and we want to get rid of "notifications to self" here).
Emails are only sent daily, and contain a digest of unread notifications.

**Comment by mamadoutoure** [comment]
Ok, so the emails are sent like in batch mode ? so What you need now is to get rid of  the insert in notiifcations table when it's a self comment ?

Merci

**Comment by mezis** [comment]
Exactly.

**Comment by mamadoutoure** [comment]
Hi Mezis,

I checked the code, and good new ! the functionality (preventing to get notified when it's our own comment on an idea) has already been implemented in the comment observer on this line:

 next if user == record.author # don't get notified for my own comments

My DB was corrupted during the first attempt, because there were like to different users on my user_bookmarks table. I cleared the DB and restarted from scratch, and everythink works fine now !

Bonne soiree

**Comment by mezis** [comment]
Oh dear, I had no idea this had been addressed already. I added the issue following user reports!
Sometimes users don't really know I suppose :)

I'll do a regression test on this. Thanks anyways!
