### ISSUE TITLE
AJAXify notifications listing

### ISSUE THREAD

**Issue by mezis** [mezis/appfab#24]
State changes and filter should not reload the whole page.

**Comment by mezis** [comment]
Staged.

**Comment by mezis** [comment]
Only addressed state change, filters still reload the page for now.

**Comment by maxhousetrip** [comment]
Ajax stuff is working fine, but new notifications are now by default marked as ticked. When you untick the Ajax saving does its stuff. But the notifications should be marked as unticked by default (I don't have any issues on Prod but pretty sure that they are unchecked by default currently).

**Comment by maxhousetrip** [comment]
Re-tested and checkbox now works fine. Accepting.
