### ISSUE TITLE
Graveyard and archived idea states

### ISSUE THREAD

**Issue by mezis** [mezis/appfab#26]
"graveyard" state for submitted ideas we no longer want, and an "archived" state for the live stories when it gets too big.

Add an extra button in the idea's action panel. This should be available to the idea author and all PMs (until "voted" inclusive), the idea's PM (from "picked" onwards), and account owners (all states).

**Comment by thejspr** [comment]
I think this would be a very useful way to reduce "noise" on boards. I suggest we take the same approach as Trello, where any idea can be archived at any time. This removed it from the board/index, so we should have a page for archived ideas. It should also be possible to unarchive the idea, putting it back to the state it was in when archived.

**Comment by mezis** [comment]
What I had in mind is that both would simply be new state on the FSM, with `draft...signed_off -> graveyard`  and `live -> archived` transitions.

Graveyarded ideas would have to be submitted for vetting again, and archived ides would just stay there for reference.

Both transitions would cause bookmarks to the ideas to be removed (after notifications).

I'm kind of hesitant to start this before having a search engine though, as there would be no obvious way to reach them (except for authors) afterwards.

**Comment by marcusleemitchell** [comment]
I'm going to grab this one and run with it...having noticed that AppFab does now have searching =]

**Comment by thejspr** [comment]
This is now live
