### ISSUE TITLE
Fix product manager user name layout

### ISSUE THREAD

**Issue by mantonini** [mezis/appfab#36]
[ Product Manager: Name | Karma Points | Karma icon ] needs to be on one line otherwise it breaks the design

![appfab feedback](https://f.cloud.github.com/assets/2444154/231706/1602616a-8710-11e2-90b3-0a0f80533278.png)

**Comment by dawid-sklodowski** [comment]
First contribution! :)

**Comment by mantonini** [comment]
Thanks Dawid
