### ISSUE TITLE
Star idea ratings

### ISSUE THREAD

**Issue by mezis** [mezis/appfab#46]
The numeric star ratings are ugly and not very readable.

Instead of a star with a figure, use zero to 4 stars, for the lower 20% of rated ideas to the top 20% rated.

As a nice side effect this will make it easier for product managers to sell that they're not picking from the top of the queue, just from the "top rated" ideas.

**Comment by mezis** [comment]
Staged.

**Comment by maxhousetrip** [comment]
Vet view doesn't seem to show the star ratings?

https://appfab-staging.herokuapp.com/ideas?angle=vettable

Are 0 stars the 1 star which is not coloured in? If so then these only seem to be present in some views, not others? If not then why is 1-star not coloured in?

**Comment by mezis** [comment]
Addressed this orally, but for the sake of leaving a trace:

> Vet view doesn't seem to show the star ratings

because at this stage ther are not votes (yet), so no impact can be computed.

> Are 0 stars the 1 star which is not coloured in?

Yes, that's correct.

> If so then these only seem to be present in some views, not others? 

See answer to the first question.

Also worth noting, "by impact" is now the default sort oreder in all views. It falls back to "by activity" when impact is absent (i.e. the "submitted" column will always have the most recently active ideas on top, the "voted one the most impactful).

Merging !
