### ISSUE TITLE
Marked one notification unread, it wiped them all!

### ISSUE THREAD

**Issue by cathrooney** [mezis/appfab#72]
I clicked to mark one notification read, and it marked them all (I had 6) read.

I have also just received my daily e-mail overview so not sure if that wipes them and therefore the timing was coincidental.

**Comment by maxhousetrip** [comment]
Daily email does mark them as read. The emails say:

"We've marked these notifications as read for you, so we won't bug you
again."

**Comment by mezis** [comment]
I believe this is related to the email marking as read, indeed. Could not reproduce either.
