### ISSUE TITLE
Flatten design, lighten font, less invasive flashes 

### ISSUE THREAD

**Issue by mezis** [mezis/appfab#82]

**Comment by mezis** [comment]
Staged.

**Comment by maxhousetrip** [comment]
I must be honest and say I'm not hugely keen.

**Comment by mezis** [comment]
> I must be honest and say I'm not hugely keen.

:laughing: I knew this was going to be a divisive issue.

At least its (a) more readable, and (b) has a personality, what do you think?

**Comment by mezis** [comment]
Is that a case of British polite understatement?
(Also, it seems no one likes it much so far)
—
Julien Letessier

**Comment by mezis** [comment]
Staged again, hopefully more consensual now.

**Comment by maxhousetrip** [comment]
Staging seems to be down (500 error)?

**Comment by mezis** [comment]
Crapola, forgot to run migrations.
I'll ping this thread once I've fixe things--sorry.
—
Julien Letessier

**Comment by mezis** [comment]
Re-staged.

**Comment by mezis** [comment]
This has now been merged, closing.
